site_name: Open World Agents
site_description: A modular agent system with dynamic module registration and real-time event processing
repo_url: https://github.com/yourusername/open-world-agents
repo_name: open-world-agents

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [projects]
          options:
            docstring_style: google
            show_source: true
  - git-revision-date-localized:
      type: datetime
  - mermaid

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Project Overview: project_overview.md
  - Architecture:
      - Core Components: architecture/core_components.md
      - Registry Pattern: architecture/registry_pattern.md
      - Event System: architecture/event_system.md
  - Modules:
      - Standard Environment: modules/std_env.md
      - Desktop Environment: modules/desktop_env.md
  - Examples:
      - Basic Usage: examples/basic_usage.md
      - Custom Extensions: examples/custom_extensions.md
  - Contributing: contributing.md
  - API Reference: api_reference.md
