[project]
name = "open-world-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "owa",
]

[dependency-groups]
dev = [
    "ipython>=8.32.0",
    "pytest>=8.3.4",
    "ruff>=0.9.4",
]

[tool.uv.sources]
owa = { path = "projects/core", editable = true }
