[project]
name = "decoding-triton-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "av>=14.2.0",
    "loguru>=0.7.3",
    "numpy>=2.2.3",
    "pillow>=11.1.0",
]


