name: Pytest on Windows

on:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Miniconda
        id: conda_setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          mamba-version: "*"
          channels: conda-forge
          conda-remove-defaults: "true"
          environment-file: projects/owa-env-gst/environment.yml
          activate-environment: owa

      - name: Export environment variables
        # This step writes dynamic variables to $GITHUB_ENV so subsequent steps can use them
        run: |
          echo "UV_PROJECT_ENVIRONMENT=${{ steps.conda_setup.outputs.base-conda-dir }}\\envs\\owa" >> $GITHUB_ENV
          echo "GST_PLUGIN_PATH=${{ github.workspace }}\\projects\\owa-env-gst\\gst-plugins" >> $GITHUB_ENV

      - name: Install dependencies using uv
        run: uv sync --dev

      - name: Run pytest
        run: uv run pytest