name: Pytest on Windows

on:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run pytest
      run: uv run pytest