name: Pytest on Windows

on:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: projects/owa-env-gst/environment.yml
          miniforge-version: latest
          mamba-version: "*"

      - name: Write environment into .env
        run: echo "UV_PROJECT_ENVIRONMENT=(conda env)" >> .env

      - name: Install dependencies
        run: uv sync --dev

      - name: Run pytest
        run: uv run pytest