name: Pytest on Windows

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: windows-latest

    env:
      UV_PROJECT_ENVIRONMENT: "C:\\Users\\runneradmin\\miniconda3\\envs\\owa"
      GST_PLUGIN_PATH: "D:\\a\\open-world-agents\\open-world-agents\\projects\\owa-env-gst\\gst-plugins"
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          mamba-version: "*"
          channels: conda-forge
          conda-remove-defaults: "true"
          environment-file: projects/owa-env-gst/environment.yml
          activate-environment: owa

      - name: Install dependencies (will pick up UV_PROJECT_ENVIRONMENT automatically)
        run: uv sync --inexact --dev --extra env # turn on --inexact to prevent removing gst packages

      - name: Run pytest (will also pick it up)
        run: |
          pytest projects/core
          pytest projects/owa-env-desktop
